# Generated by Django 5.2.1 on 2025-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_author_dob_author_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(),
        ),
    ]
