# Generated by Django 5.2.1 on 2025-07-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
