# Generated by Django 5.2.1 on 2025-06-17 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateField(default=datetime.date(2025, 6, 17)),
        ),
        migrations.AddField(
            model_name='author',
            name='dod',
            field=models.DateField(null=True),
        ),
    ]
