# Generated by Django 5.2.1 on 2025-06-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('user', '0002_author_dob_author_dod'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('Y', 'YORUBA'), ('I', 'IGBO'), ('C', 'CALABA ')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1, unique=True),
        ),
    ]
